;;**************************************
;;;;  GLOBAL KEYBINDINGS **
(global-set-key     (kbd "RET")               'newline-and-indent)
(global-set-key     (kbd "C-l")               'goto-line)
(global-set-key     (kbd "M-;")               'comment-dwim)
                                        ;(windmove-default-keybindings 'shift)
(global-set-key (kbd "C-S-n") (lambda () (interactive) (ignore-errors (next-line 10))))
(global-set-key (kbd "C-S-p") (lambda () (interactive) (ignore-errors (previous-line 10))))
(global-set-key (kbd "C-S-f") (lambda () (interactive) (ignore-errors (forward-char 10))))
(global-set-key (kbd "C-S-b") (lambda () (interactive) (ignore-errors (backward-char 10))))
(global-set-key     (kbd "<select>")          'windmove-up)
(global-set-key     (kbd "C-x r l")           'list-register)
(global-set-key     (kbd "C-c d")             'backward-kill-word)
(global-set-key     (kbd "C-c C-k")           'kill-region)
(global-set-key     (kbd "M-<")               'beginning-of-buffer)
(global-set-key (kbd "C-c m d") 'move-line-down)
(global-set-key (kbd "C-c m u") 'move-line-up)
(global-set-key     (kbd "M->")               'end-of-buffer)
(global-set-key     (kbd "C-c C-d l")         'delete-blank-lines)
(global-set-key     (kbd "C-c C-c k")         'delete-current-buffer-file)
(global-set-key     (kbd "C-c e b")           'cleanup-buffer)
(global-set-key     (kbd "C-c C-c C-r")       'rename-current-buffer-file)
(global-set-key     (kbd "C-x o")             (lambda () (interactive) (other-window -1)))
(global-set-key     (kbd "C-x O")             (lambda () (interactive) (other-window 1)))
(global-set-key     (kbd "C-h C-f")           'find-function)
(global-set-key     (kbd "C-h C-k")           'find-function-on-key)
(global-set-key     (kbd "C-h C-v")           'find-variable)
(global-set-key     (kbd "C-h C-l")           'find-library)
(global-set-key     (kbd "C-c C-f")           'fold-dwim-toggle)
(global-set-key     (kbd "C-SPC")             'set-mark-command)
(global-set-key     (kbd "C-x C-SPC")       'pop-global-mark)
(global-set-key     (kbd "C-c C-SPC")       'unpop-to-mark-command)
(global-set-key (kbd "<C-tab>") 'bury-buffer)
(define-key global-map (kbd "C-;") 'iedit-mode)
(global-set-key (kbd "C-x 2") 'vertically-split-last-buffer)
(global-set-key (kbd "C-x 3") 'horizontally-split-last-buffer)
(global-set-key (kbd "C-x |") 'toggle-window-split)
(global-set-key (kbd "C-c |") 'rotate-windows)
(global-set-key (kbd "C-c C-c r") 'search-current-word-backward)
(global-set-key (kbd "C-c C-c s") 'search-current-word-forward)
(global-set-key [remap move-beginning-of-line]
                'smarter-move-beginning-of-line)
(global-set-key (kbd "C-x C-r") 'ido-recentf-open)
(bind-key "C-M-<backspace>" 'kill-back-to-indentation)
(global-set-key (kbd "C-s") 'phi-search)
(global-set-key (kbd "C-r") 'phi-search-backward)
(global-set-key (kbd "C-c C-w") 'ace-window)
(global-set-key (kbd "C-x O") 'ace-window)
(global-set-key (kbd "M-z") 'ace-jump-zap-up-to-char-dwim)
(global-set-key (kbd "M-Z") 'ace-jump-zap-to-char-dwim)
(global-set-key (kbd "C-c c") 'copy-region-as-kill)
(global-set-key (kbd "M-j") (lambda () (interactive) (join-line -1)))
(global-set-key (kbd "M-c") (lambda () (interactive) (shell-command-on-region (region-beginning) (region-end) "pbcopy")))
;;**************************************
(provide 'kbd-config)
